### ISSUE TITLE
Issue-Initial commit

### ISSUE THREAD

**Issue by lunarforky-z** [lunarforky-z/near-sweat01#2]
Automated Review Comments
Issues in Cargo.lock:
  - (7, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (131, 'Hardcoded string found')
  - (136, 'Hardcoded string found')
  - (147, 'Hardcoded string found')
  - (149, 'Hardcoded string found')
  - (153, 'Hardcoded string found')
  - (167, 'Hardcoded string found')
  - (172, 'Hardcoded string found')
  - (177, 'Hardcoded string found')
  - (181, 'Hardcoded string found')
  - (187, 'Hardcoded string found')
  - (193, 'Hardcoded string found')
  - (198, 'Hardcoded string found')
  - (203, 'Hardcoded string found')
  - (209, 'Hardcoded string found')
  - (221, 'Hardcoded string found')
  - (227, 'Hardcoded string found')
  - (254, 'Hardcoded string found')
  - (257, 'Hardcoded string found')
  - (260, 'Hardcoded string found')
  - (272, 'Hardcoded string found')
  - (273, 'Hardcoded string found')
  - (275, 'Hardcoded string found')
  - (286, 'Hardcoded string found')
  - (287, 'Hardcoded string found')
  - (289, 'Hardcoded string found')
  - (299, 'Hardcoded string found')
  - (309, 'Hardcoded string found')
  - (314, 'Hardcoded string found')
  - (325, 'Hardcoded string found')
  - (327, 'Hardcoded string found')
  - (328, 'Hardcoded string found')
  - (339, 'Hardcoded string found')
  - (340, 'Hardcoded string found')
  - (349, 'Hardcoded string found')
  - (350, 'Hardcoded string found')
  - (352, 'Hardcoded string found')
  - (362, 'Hardcoded string found')
  - (364, 'Hardcoded string found')
  - (368, 'Hardcoded string found')
  - (379, 'Hardcoded string found')
  - (390, 'Hardcoded string found')
  - (400, 'Hardcoded string found')
  - (404, 'Hardcoded string found')
  - (413, 'Hardcoded string found')
  - (423, 'Hardcoded string found')
  - (437, 'Hardcoded string found')
  - (450, 'Hardcoded string found')
  - (459, 'Hardcoded string found')
  - (465, 'Hardcoded string found')
  - (481, 'Hardcoded string found')
  - (485, 'Hardcoded string found')
  - (491, 'Hardcoded string found')
  - (505, 'Hardcoded string found')
  - (509, 'Hardcoded string found')
  - (524, 'Hardcoded string found')
  - (525, 'Hardcoded string found')
  - (534, 'Hardcoded string found')
  - (535, 'Hardcoded string found')
  - (536, 'Hardcoded string found')
  - (537, 'Hardcoded string found')
  - (548, 'Hardcoded string found')
  - (549, 'Hardcoded string found')
  - (560, 'Hardcoded string found')
  - (561, 'Hardcoded string found')
  - (566, 'Hardcoded string found')
  - (572, 'Hardcoded string found')
  - (585, 'Hardcoded string found')
  - (590, 'Hardcoded string found')
  - (594, 'Hardcoded string found')
  - (624, 'Hardcoded string found')
  - (626, 'Hardcoded string found')
  - (630, 'Hardcoded string found')
Issues in Cargo.toml:
  - (10, 'Line exceeds 80 characters')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
Issues in sweat-coin/Cargo.lock:
  - (7, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (24, 'Hardcoded string found')
  - (28, 'Hardcoded string found')
  - (56, 'Hardcoded string found')
  - (62, 'Hardcoded string found')
  - (75, 'Hardcoded string found')
  - (85, 'Hardcoded string found')
  - (86, 'Hardcoded string found')
  - (96, 'Hardcoded string found')
  - (97, 'Hardcoded string found')
  - (107, 'Hardcoded string found')
  - (137, 'Hardcoded string found')
  - (138, 'Hardcoded string found')
  - (142, 'Hardcoded string found')
  - (156, 'Hardcoded string found')
  - (161, 'Hardcoded string found')
  - (166, 'Hardcoded string found')
  - (170, 'Hardcoded string found')
  - (176, 'Hardcoded string found')
  - (181, 'Hardcoded string found')
  - (182, 'Hardcoded string found')
  - (186, 'Hardcoded string found')
  - (192, 'Hardcoded string found')
  - (204, 'Hardcoded string found')
  - (210, 'Hardcoded string found')
  - (237, 'Hardcoded string found')
  - (240, 'Hardcoded string found')
  - (243, 'Hardcoded string found')
  - (255, 'Hardcoded string found')
  - (256, 'Hardcoded string found')
  - (258, 'Hardcoded string found')
  - (269, 'Hardcoded string found')
  - (270, 'Hardcoded string found')
  - (272, 'Hardcoded string found')
  - (282, 'Hardcoded string found')
  - (292, 'Hardcoded string found')
  - (297, 'Hardcoded string found')
  - (308, 'Hardcoded string found')
  - (310, 'Hardcoded string found')
  - (311, 'Hardcoded string found')
  - (322, 'Hardcoded string found')
  - (323, 'Hardcoded string found')
  - (332, 'Hardcoded string found')
  - (333, 'Hardcoded string found')
  - (335, 'Hardcoded string found')
  - (345, 'Hardcoded string found')
  - (347, 'Hardcoded string found')
  - (351, 'Hardcoded string found')
  - (362, 'Hardcoded string found')
  - (373, 'Hardcoded string found')
  - (383, 'Hardcoded string found')
  - (387, 'Hardcoded string found')
  - (396, 'Hardcoded string found')
  - (417, 'Hardcoded string found')
  - (430, 'Hardcoded string found')
  - (439, 'Hardcoded string found')
  - (445, 'Hardcoded string found')
  - (457, 'Hardcoded string found')
  - (463, 'Hardcoded string found')
  - (478, 'Hardcoded string found')
  - (479, 'Hardcoded string found')
  - (488, 'Hardcoded string found')
  - (489, 'Hardcoded string found')
  - (490, 'Hardcoded string found')
  - (491, 'Hardcoded string found')
  - (503, 'Hardcoded string found')
  - (514, 'Hardcoded string found')
  - (515, 'Hardcoded string found')
  - (520, 'Hardcoded string found')
  - (526, 'Hardcoded string found')
  - (548, 'Hardcoded string found')
  - (553, 'Hardcoded string found')
  - (557, 'Hardcoded string found')
  - (581, 'Hardcoded string found')
  - (583, 'Hardcoded string found')
  - (587, 'Hardcoded string found')
Issues in sweat-coin/Cargo.toml:
  - (10, 'Hardcoded string found')
  - (15, 'Line exceeds 80 characters')
Issues in sweat-coin/build.sh:
  - (5, 'Line exceeds 80 characters')
Issues in sweat-coin/src/lib.rs:
  - (8, 'Line exceeds 80 characters')
  - (29, 'Hardcoded string found')
  - (54, 'Line exceeds 80 characters')
  - (68, 'Hardcoded string found')
  - (69, 'Hardcoded string found')

**Comment by hylcore-V** [comment]
I got it.
